### PR TITLE
Complete rewrite

### PR DESCRIPTION
**Pull request by mnieper**
This pull request should be the basis of the next draft.

### CODE REVIEW

**Comment by arthurgleckler** [comment]
Thanks.  I've merged your changes, and have made a bunch of small copy edits.  Please check that I haven't made any mistakes.

I have three other requests:

1. Add simple examples.
2. In the section where you define tail recursion formally, it would be good to give an English explanation of the mathematical definition you propose.
3. There is no text describing `transport-cell-value`.

I'll wait for your reply before publishing a new draft.

Thanks.

**Comment by mnieper** [comment]
Thank you!

Am Sa., 14. Sept. 2024 um 02:14 Uhr schrieb Arthur A. Gleckler <
***@***.***>:

> Thanks. I've merged your changes, and have made a bunch of small copy
> edits. Please check that I haven't made any mistakes.
>
I am going to comment directly on GitHub where it shows me the changes, if
it is okay.

(I am sorry for all the a/an mistakes; I changed some terms with
search&replace in the course of the creation of the document; some leading
vowels became consonants.)

> I have three other requests:
>
>    1. Add simple examples.
>
> This is on my issue list.

>
>    1. In the section where you define tail recursion formally, it would
>    be good to give an English explanation of the mathematical definition you
>    propose.
>
> I am going to add a non-normative sentence.


>
>    1. There is no text describing transport-cell-value.
>
> I am going to fix this.


>
>
> I'll wait for your reply before publishing a new draft.
>
> Thanks.
>
Thanks.

Marc

**Comment by mnieper** [comment]
Follow-up:


1. Please add the following HTML for the description of
transport-cell-value:

    <p>The <code>transport-cell-key</code> procedure returns the contents
      of the value field of <var>transport-cell</var>.
    </p>

2. Please add the following HTML directly after the paragraph that holds
the blockquote:

    <p><i>Comment:</i> This extension of the proper tail recursive
      semantics says that the values stored in weakly holding locations are
      ignored when the garbage collector determines the locations that
      can be reclaimed.</p>

3. I nested <blockquote> within <p>, which is likely invalid HTML.  Please
replace that HTML with

    <p>As specified in the reports on Scheme, implementations of
      Scheme are required to be properly tail-recursive.  The formal
      definition of proper tail-recursion can be found
      in <cite><a href="#clinger">[2]</a></cite>.  This SRFI extends
      the property tail recursive semantics in <cite>[2]</cite> by
replacing the last line
    </p>
    <blockquote>
      <p>
        and <var>&beta;</var>, &hellip; do not occur
        within <var>v</var>, <var>&rho;</var>, <var>&kappa;</var>,
<var>&sigma;</var>
      </p>
    </blockquote>
    <p>
      in the garbage collection rule with
    </p>
    <blockquote>
      <p>
        and <var>&beta;</var>, &hellip; do not occur
        within <var>v</var>, <var>&rho;</var>, <var>&kappa;</var>,
<var>&sigma;'</var>
        where <var>&sigma;</var>
        = <var>&sigma;'</var>[<var>&beta;'</var>, &hellip;
        &mapsto; <var>v''</var>, &hellip;] and <var>&beta;'</var> are
        weakly holding.
      </p>
    </blockquote>

When the fixes are done, I will work on the examples based on the fixed
document (to minimize merge problems later).

Thanks again,

Marc

Am Sa., 14. Sept. 2024 um 08:32 Uhr schrieb Marc Nieper-Wißkirchen <
***@***.***>:

**Comment by arthurgleckler** [comment]
On Fri, Sep 13, 2024 at 11:33 PM Marc Nieper-Wißkirchen <
***@***.***> wrote:


> I am going to comment directly on GitHub where it shows me the changes, if
> it is okay.
>

No problem.  The Git repo contains the history of the changes, so it's okay
if it's not on the mailing list.

I've now addressed them all.


> (I am sorry for all the a/an mistakes; I changed some terms with
> search&replace in the course of the creation of the document; some leading
> vowels became consonants.)
>

It's an easy mistake to make.  I've never used a grammar checker because
they haven't been reliable.  I'm hoping that LLMs will make them as
reliable as spelling checkers.


> > 1. Add simple examples.
> >
> > This is on my issue list.
>

Sorry, I missed that.

On Fri, Sep 13, 2024 at 11:50 PM Marc Nieper-Wißkirchen <
***@***.***> wrote:

> Follow-up:
>
>
> 1. Please add the following HTML for the description of
> transport-cell-value:
>
> <p>The <code>transport-cell-key</code> procedure returns the contents
> of the value field of <var>transport-cell</var>.
> </p>


Done, except that I changed it to transport-cell-value.

>
>
2. Please add the following HTML directly after the paragraph that holds
> the blockquote:
>
> <p><i>Comment:</i> This extension of the proper tail recursive
> semantics says that the values stored in weakly holding locations are
> ignored when the garbage collector determines the locations that
> can be reclaimed.</p>
>

Perfect.


> 3. I nested <blockquote> within <p>, which is likely invalid HTML. Please
> replace that HTML with


Done.

When the fixes are done, I will work on the examples based on the fixed
> document (to minimize merge problems later).
>

 They're all done and pushed.

**Pull request merged**
